# Generated by Django 4.2.6 on 2023-11-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
