# Generated by Django 4.2.6 on 2023-11-26 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_evento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['fecha_inicio'], 'permissions': {('ingresar_privado', 'puede ingresar a la vista privada'), ('ingresar_api', 'puede ingresar a la apli')}, 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
